[vfs-url]
# India to destinations
IN-DE = https://visa.vfsglobal.com/ind/en/deu/login
IN-IT = https://visa.vfsglobal.com/ind/en/ita/login
IN-GB = https://visa.vfsglobal.com/ind/en/gbr/login

# Nigeria to destinations
NG-DE = https://visa.vfsglobal.com/nga/en/deu/login
NG-GB = https://visa.vfsglobal.com/nga/en/gbr/login
NG-CA = https://visa.vfsglobal.com/nga/en/can/login
NG-IT = https://visa.vfsglobal.com/nga/en/ita/login

# Ghana to destinations
GH-DE = https://visa.vfsglobal.com/gha/en/deu/login
GH-GB = https://visa.vfsglobal.com/gha/en/gbr/login
GH-CA = https://visa.vfsglobal.com/gha/en/can/login

# Kenya to destinations
KE-DE = https://visa.vfsglobal.com/ken/en/deu/login
KE-GB = https://visa.vfsglobal.com/ken/en/gbr/login

# South Africa to destinations
ZA-DE = https://visa.vfsglobal.com/zaf/en/deu/login
ZA-GB = https://visa.vfsglobal.com/zaf/en/gbr/login

# Iraq to destinations
IQ-DE = https://visa.vfsglobal.com/irq/en/deu/login

# Morocco to destinations
MA-IT = https://visa.vfsglobal.com/mar/en/ita/login

# Azerbaijan to destinations  
AZ-IT = https://visa.vfsglobal.com/aze/en/ita/login
